name: Gatekeeper

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Gatekeeping:
    name: Gatekeeping
    runs-on: ubuntu-18.04
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set .NET Core version
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.205"

      - name: Nuget cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Pack
        run: |
          dotnet pack Strapi.AspNet.Annotations/Strapi.AspNet.Annotations.csproj --nologo --configuration Release
          dotnet pack Strapi.AspNet.Hosting/Strapi.AspNet.Hosting.csproj --nologo --configuration Release
          dotnet pack Strapi.AspNet.DataModel/Strapi.AspNet.DataModel.csproj --nologo --configuration Release
          dotnet pack Strapi.AspNet.Engine/Strapi.AspNet.Engine.csproj --nologo --configuration Release
          dotnet pack Strapi.AspNet.Cms/Strapi.AspNet.Cms.csproj --nologo --configuration Release

